### ISSUE TITLE
Related to PHPMyAdmin

### ISSUE THREAD

**Issue by ghost** [barreiros/GorillaJS#2]
Hi.

I have been working with GorillaJS. I think is an awesome node module.  I think i found a bug and maybe you want to check this one.  

When i execute gorilla init command and the machine has been lifted. Then go to the url of my project and try to acccess to phpMyAdmin.

http://url-of-the-project/phpMyAdmin

Access with the user and password that i previously created when setup GorillaJS successfully. But when i try to access to some database, or execute a SQL command returns an error.

Error #1142 - SELECT command denied to user USER@IP for table pma_table_uiprefs

I have been checking this error and i think the pma_table_uiprefs table contains user preferences.

In phpMyAdmin's config.inc.php, access to this table (and other tables in the configuration storage) is done via the control user. In your case, the controluser parameter is empty, therefore the query fails.

https://docs.phpmyadmin.net/en/latest/setup.html#phpmyadmin-configuration-storage

Please, could you check this and fix it in the project. 

Best regards.

**Comment by barreiros** [comment]
Hi, dharmawebstudio.

The problem was my custom phpmyadmin configuration: GorillaJS use separate containers and database host is not the default "localhost". 

I will add this fix in the next version (0.2.5).

Thanks!
